# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '48c6db67-004a-4ea3-af6b-24eed888d054'
  imageRepository: 'frontstudy' # nome da imagem
  containerRegistry: 'ccflabs.azurecr.io' # nome do container registry
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile' # caminho do Dockerfile
  tag: '$(Build.BuildId)'   

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy to Azure Web App
      inputs:
        azureSubscription: 'study-deployments'   # conexão ARM estabelecida durante a criação do pipeline
        appName: 'frontstudy'                   # nome do App Service
        containers: '$(containerRegistry)/$(imageRepository):$(tag)'

